# SPDX-FileCopyrightText: 2015-2022 Alexey Rochev
#
# SPDX-License-Identifier: CC0-1.0

Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-#{ENV["FREEBSD_VERSION"]}"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.synced_folder ENV["GITHUB_WORKSPACE"], "/workspace", type: "rsync"
  config.vm.provider "virtualbox" do |v|
    v.memory = [`sysctl -n hw.memsize`.to_i / 1048576 - 1024, 1024].max
    v.cpus = [`sysctl -n hw.ncpu`.to_i, 1].max
  end
end
